import { Product, CategoryItem } from './types';

export const CATEGORIES_DATA: CategoryItem[] = [
    { id: 'all', name: 'Todas', imageUrl: 'https://picsum.photos/seed/cat_all/100/100' },
    { id: 'Electrónicos', name: 'Electrónicos', imageUrl: 'https://picsum.photos/seed/cat_electronics/100/100' },
    { id: 'Ropa', name: 'Ropa', imageUrl: 'https://picsum.photos/seed/cat_clothes/100/100' },
    { id: 'Hogar', name: 'Hogar', imageUrl: 'https://picsum.photos/seed/cat_home/100/100' },
    { id: 'Libros', name: 'Libros', imageUrl: 'https://picsum.photos/seed/cat_books/100/100' },
];

export const MOCK_PRODUCTS: Product[] = [
    {
        id: 1,
        name: 'Smartphone Pro X',
        description: 'El último modelo con cámara de 108MP y 5G.',
        price: 799.99,
        category: 'Electrónicos',
        imageUrls: [
            'https://picsum.photos/seed/smartphone/800/800',
            'https://picsum.photos/seed/smartphone_angle/800/800',
            'https://picsum.photos/seed/smartphone_case/800/800',
            'https://picsum.photos/seed/smartphone_box/800/800',
        ],
        inStock: true,
        featured: true,
        createdAt: '2023-10-26T10:00:00Z',
    },
    {
        id: 2,
        name: 'Auriculares Inalámbricos',
        description: 'Sonido inmersivo y cancelación de ruido activa.',
        price: 129.50,
        category: 'Electrónicos',
        imageUrls: [
            'https://picsum.photos/seed/headphones/800/800',
            'https://picsum.photos/seed/headphones_case/800/800',
            'https://picsum.photos/seed/headphones_ear/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-10-22T11:30:00Z',
    },
    {
        id: 3,
        name: 'Camiseta de Algodón',
        description: 'Suave, cómoda y perfecta para el uso diario.',
        price: 25.00,
        category: 'Ropa',
        imageUrls: [
            'https://picsum.photos/seed/tshirt/800/800',
            'https://picsum.photos/seed/tshirt_folded/800/800',
            'https://picsum.photos/seed/tshirt_model/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-09-15T09:00:00Z',
    },
    {
        id: 4,
        name: 'Jeans Clásicos',
        description: 'Un corte atemporal que nunca pasa de moda.',
        price: 60.00,
        category: 'Ropa',
        imageUrls: [
            'https://picsum.photos/seed/jeans/800/800',
            'https://picsum.photos/seed/jeans_detail/800/800',
            'https://picsum.photos/seed/jeans_back/800/800',
        ],
        inStock: false,
        featured: false,
        createdAt: '2023-09-20T14:00:00Z',
    },
    {
        id: 5,
        name: 'Lámpara de Escritorio LED',
        description: 'Iluminación ajustable para tu espacio de trabajo.',
        price: 45.99,
        category: 'Hogar',
        imageUrls: [
            'https://picsum.photos/seed/lamp/800/800',
            'https://picsum.photos/seed/lamp_on/800/800',
            'https://picsum.photos/seed/lamp_desk/800/800',
        ],
        inStock: true,
        featured: true,
        createdAt: '2023-10-10T18:00:00Z',
    },
    {
        id: 6,
        name: 'Juego de Sábanas Queen',
        description: 'Microfibra de alta calidad para un sueño reparador.',
        price: 89.99,
        category: 'Hogar',
        imageUrls: [
            'https://picsum.photos/seed/sheets/800/800',
            'https://picsum.photos/seed/sheets_bed/800/800',
            'https://picsum.photos/seed/sheets_folded/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-08-05T12:00:00Z',
    },
    {
        id: 7,
        name: 'El Arte de Programar',
        description: 'Una guía esencial para desarrolladores de software.',
        price: 35.50,
        category: 'Libros',
        imageUrls: [
            'https://picsum.photos/seed/book1/800/800',
            'https://picsum.photos/seed/book1_open/800/800',
            'https://picsum.photos/seed/book1_stack/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-10-25T16:45:00Z',
    },
    {
        id: 8,
        name: 'Ciencia Ficción: La Saga',
        description: 'Un viaje épico a través de galaxias lejanas.',
        price: 22.00,
        category: 'Libros',
        imageUrls: [
            'https://picsum.photos/seed/book2/800/800',
            'https://picsum.photos/seed/book2_side/800/800',
        ],
        inStock: false,
        featured: false,
        createdAt: '2023-07-30T20:00:00Z',
    },
    {
        id: 9,
        name: 'Laptop Ultraligera',
        description: 'Potencia y portabilidad en un diseño elegante.',
        price: 1200.00,
        category: 'Electrónicos',
        imageUrls: [
            'https://picsum.photos/seed/laptop/800/800',
            'https://picsum.photos/seed/laptop_open/800/800',
            'https://picsum.photos/seed/laptop_side/800/800',
            'https://picsum.photos/seed/laptop_keyboard/800/800',
        ],
        inStock: true,
        featured: true,
        createdAt: '2023-10-18T08:20:00Z',
    },
    {
        id: 10,
        name: 'Sudadera con Capucha',
        description: 'Abrigo y estilo para los días más fríos.',
        price: 55.00,
        category: 'Ropa',
        imageUrls: [
            'https://picsum.photos/seed/hoodie/800/800',
            'https://picsum.photos/seed/hoodie_model/800/800',
            'https://picsum.photos/seed/hoodie_back/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-10-01T13:10:00Z',
    },
    {
        id: 11,
        name: 'Cafetera de Goteo',
        description: 'Prepara el café perfecto cada mañana fácilmente.',
        price: 75.00,
        category: 'Hogar',
        imageUrls: [
            'https://picsum.photos/seed/coffee/800/800',
            'https://picsum.photos/seed/coffee_making/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-09-11T07:00:00Z',
    },
    {
        id: 12,
        name: 'Historia del Mundo',
        description: 'Un recorrido completo por los eventos clave de la humanidad.',
        price: 40.00,
        category: 'Libros',
        imageUrls: [
            'https://picsum.photos/seed/book3/800/800',
            'https://picsum.photos/seed/book3_open/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-10-27T10:00:00Z',
    },
    {
        id: 13,
        name: 'Monitor Curvo 27"',
        description: 'Experiencia inmersiva para gaming y trabajo.',
        price: 350.00,
        category: 'Electrónicos',
        imageUrls: [
            'https://picsum.photos/seed/monitor/800/800',
            'https://picsum.photos/seed/monitor_desk/800/800',
            'https://picsum.photos/seed/monitor_side/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-11-01T10:00:00Z',
    },
    {
        id: 14,
        name: 'Vestido de Verano',
        description: 'Ligero y fresco para los días calurosos.',
        price: 49.99,
        category: 'Ropa',
        imageUrls: [
            'https://picsum.photos/seed/dress/800/800',
            'https://picsum.photos/seed/dress_model/800/800',
            'https://picsum.photos/seed/dress_fabric/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-10-30T11:30:00Z',
    },
    {
        id: 15,
        name: 'Set de Cuchillos',
        description: 'Acero inoxidable de alta calidad para tu cocina.',
        price: 110.00,
        category: 'Hogar',
        imageUrls: [
            'https://picsum.photos/seed/knives/800/800',
            'https://picsum.photos/seed/knives_block/800/800',
            'https://picsum.photos/seed/knives_use/800/800',
        ],
        inStock: false,
        featured: false,
        createdAt: '2023-10-29T18:00:00Z',
    },
    {
        id: 16,
        name: 'Novela de Misterio',
        description: 'Un thriller que no podrás dejar de leer.',
        price: 19.95,
        category: 'Libros',
        imageUrls: [
            'https://picsum.photos/seed/book4/800/800',
        ],
        inStock: true,
        featured: false,
        createdAt: '2023-11-02T15:00:00Z',
    },
];

export const SLIDER_ITEMS = [
    {
        id: 1,
        title: 'Nuevas Colecciones',
        subtitle: 'Descubre las últimas tendencias',
        imageUrl: 'https://picsum.photos/seed/promo1/1200/400',
    },
    {
        id: 2,
        title: 'Ofertas Exclusivas',
        subtitle: 'Hasta 50% de descuento en electrónicos',
        imageUrl: 'https://picsum.photos/seed/promo2/1200/400',
    },
    {
        id: 3,
        title: 'Envío Gratis',
        subtitle: 'En todos los pedidos superiores a $50',
        imageUrl: 'https://picsum.photos/seed/promo3/1200/400',
    },
];